[package]
name = "rc_wrapper_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
default = []
threaded = []

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
