[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
[lib]
name = "rustlib"
# crate-type = ["cdylib"]
crate-type = ["staticlib"]
path = "src/main.rs"
[dependencies]
rustworkx-core = "0.14.2"
# pyo3 = { version = "0.21.2", features = ["extension-module"] }
rand="0.8.5"
tqdm = "0.7.0"
rstar = "0.12.0"
geo = "0.28.0"
